### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [qvalento-gtm-templates/query-string-modifier#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUri should be used on user provided values that are then used to create your url. This method returns an encoded Uniform Resource Identifier (URI) by escaping special characters. This method returns a string that represents the provided string encoded as a URI. Please use this while creating the url.
let url = data.location;

**Comment by qvalento-gtm-templates** [comment]
@praveena-pappu, It has now been fixed.
